### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by shameelkhanx** [krishiv1545/Mock-It-Yourself#1]
Can you add timer to it? 
For eg adding timer with score will help better to predict and accounts more acuracy. 
Like I attempted 20 question in 45 mins and 20 question in 1:30 hrs is all different. 

For this what I thought of is like adding section for each subject  
And divide into three lines 
Like maths : green line when question done under 3 mins 
Violet : when done more than 3-5 mins 
Red line : more than 5 mins 

For physics, chem u can set approximately the same.

**Comment by krishiv1545** [comment]
Hey @shameelkhanx 

I added a timer along with a line that slowly runs out overtime (for the whole session, not for each question) !!

![image](https://github.com/user-attachments/assets/91020947-5ecd-425e-a148-1e6d3809ec6b)


I didnt want to clog the website, I dont find the subject wise thing being useful but that brings me to another change. I've added subject wise charts to track your scores. Not what you asked for but definitely a fun add.

Thank you for your inputs. Feel free to make more suggestions.
